### ISSUE TITLE
Users not showing in 3X-UI

### ISSUE THREAD

**Issue by hoffiez** [remnawave/xtls-sdk#2]
After running `api.handler.addVlessUser` they are actually added, but not showing in the panel.

**Comment by hoffiez** [comment]
Also, after restarting xray-core, newly added users are removed completely (i.e. not accessible via `api.handler.getInboundUsers` anymore)

**Comment by kastov** [comment]
> After running `api.handler.addVlessUser` they are actually added, but not showing in the panel.

Hi, @hoffiez!

I'm don't used 3X-UI, but as i know it fully operates with XRay-Core.
Most like 3X-UI have their own internal database to handle users and configs.

If you add user and then thought SDK try to get users – newly created users will appear?

**Comment by kastov** [comment]
> Also, after restarting xray-core, newly added users are removed completely (i.e. not accessible via `api.handler.getInboundUsers` anymore)

Xray-core restarted thought 3X-UI or manually?

Usually this should work like this:

- you have users (10 for example)
- you have management interface or you use raw .json config

So then you restart core you should provide config with initial clients (10 from example above). (which persistent)

Then you adding users via XTLS-SDK (they don't persisted, cause they do not saved to config file)
